# Generated by Django 3.1.2 on 2021-01-09 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=32)),
                ('catchphrase', models.CharField(max_length=32)),
                ('short_description', models.CharField(max_length=32)),
                ('long_description', models.CharField(max_length=256)),
                ('ideal_for', models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced'), ('all', 'All')], max_length=10)),
                ('recommended_class_frequency', models.CharField(choices=[('1-3 X/week', 'One To Three Times Per Week'), ('2-3 X/week', 'Two To Four Times Per Week')], max_length=20)),
                ('what_to_expect', models.CharField(max_length=128)),
                ('what_you_need_for_class', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.coursecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SessionPackageOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_size', models.TextField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=10)),
                ('number_of_sessions', models.IntegerField()),
                ('price_per_session', models.FloatField(max_length=6)),
                ('total_price', models.FloatField(max_length=7)),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.coursecategory')),
                ('course_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.coursesubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coursesubcategory',
            name='offered_in_languages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.language'),
        ),
    ]
