# Generated by Django 3.1.2 on 2021-01-19 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActioSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conducted_on', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('about_me', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwilioRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=600, null=True)),
                ('date_created', models.DateTimeField(default=django.db.models.functions.datetime.Now)),
                ('actio_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.actiosession')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=32)),
                ('catchphrase', models.CharField(max_length=126)),
                ('short_description', models.CharField(max_length=32)),
                ('long_description', models.CharField(max_length=256)),
                ('ideal_for', models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced'), ('all', 'All')], max_length=10)),
                ('recommended_class_frequency', models.CharField(choices=[('1-3 X/week', 'One To Three Times Per Week'), ('2-3 X/week', 'Two To Four Times Per Week')], max_length=20)),
                ('what_to_expect', models.CharField(max_length=128)),
                ('what_you_need_for_class', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.coursecategory')),
                ('offered_in_languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.language')),
            ],
            options={
                'unique_together': {('subcategory', 'offered_in_languages')},
            },
        ),
        migrations.CreateModel(
            name='CoachAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('availability_identifier', models.UUIDField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.coach')),
            ],
            options={
                'unique_together': {('coach', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.AddField(
            model_name='actiosession',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.coach'),
        ),
        migrations.AddField(
            model_name='actiosession',
            name='course_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.coursecategory'),
        ),
        migrations.AddField(
            model_name='actiosession',
            name='course_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.coursesubcategory'),
        ),
        migrations.AddField(
            model_name='actiosession',
            name='session_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.coachavailability'),
        ),
        migrations.AddField(
            model_name='actiosession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SessionPackageOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_size', models.TextField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=10)),
                ('number_of_sessions', models.IntegerField()),
                ('price_per_session', models.FloatField(max_length=6)),
                ('total_price', models.FloatField(max_length=7)),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.coursecategory')),
                ('course_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.coursesubcategory')),
            ],
            options={
                'unique_together': {('course_category', 'course_subcategory', 'session_size')},
            },
        ),
        migrations.CreateModel(
            name='AmazonResourceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arn', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'arn')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='actiosession',
            unique_together={('coach', 'user', 'start_time', 'end_time', 'conducted_on')},
        ),
    ]
