# Generated by Django 3.1.2 on 2021-01-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='coach',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.coach'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='conducted_on',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='course_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.coursecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='course_subcategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.coursesubcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='session_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
