# Generated by Django 3.1.2 on 2021-01-19 21:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachavailability',
            name='availability_identifier',
        ),
        migrations.AlterField(
            model_name='coachavailability',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
