# Generated by Django 3.1.2 on 2021-01-09 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_session_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='email',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='username',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='category',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
        migrations.CreateModel(
            name='TwilioRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.session', to_field='uuid')),
            ],
        ),
    ]
