# Generated by Django 3.1.2 on 2021-01-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210109_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='about_me',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='display_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
