# Generated by Django 3.1.2 on 2021-01-09 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210109_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='coaches_course_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.coursecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='coaches_course_subcategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.coursesubcategory'),
            preserve_default=False,
        ),
    ]
