# Generated by Django 3.1.2 on 2021-01-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210109_2327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together={('username', 'phone', 'email', 'coaches_course_category', 'coaches_course_subcategory')},
        ),
    ]
