# Generated by Django 3.1.2 on 2021-01-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210109_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='coach',
            name='username',
            field=models.CharField(max_length=12),
        ),
    ]
