# Generated by Django 3.1.2 on 2021-01-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210109_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twiliorooms',
            name='session',
        ),
        migrations.AddField(
            model_name='twiliorooms',
            name='date_created',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twiliorooms',
            name='room_sid',
            field=models.CharField(default=None, max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twiliorooms',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('completed', 'Completed')], default=None, max_length=16),
            preserve_default=False,
        ),
    ]
