# Generated by Django 3.1.2 on 2021-01-10 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210109_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliorooms',
            name='access_token',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='twiliorooms',
            name='assigned_to_coach',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.coach'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twiliorooms',
            name='room_sid',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='twiliorooms',
            unique_together={('room_sid', 'assigned_to_coach', 'access_token')},
        ),
    ]
