# Generated by Django 3.1.2 on 2021-01-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210110_2327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwilioRooms',
            new_name='TwilioRoom',
        ),
    ]
