# Generated by Django 3.1.2 on 2021-01-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210111_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioroom',
            name='date_updated',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
