# Generated by Django 3.1.2 on 2021-01-12 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0016_twilioroom_date_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='ActioSession',
        ),
        migrations.RenameField(
            model_name='twilioroom',
            old_name='room',
            new_name='unique_name',
        ),
        migrations.AddField(
            model_name='twilioroom',
            name='display_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coach',
            name='username',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='twilioroom',
            name='date_created',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now),
        ),
        migrations.AlterUniqueTogether(
            name='actiosession',
            unique_together={('coach', 'user', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='twilioroom',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coach',
            name='coaches_course_category',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='coaches_course_subcategory',
        ),
        migrations.RemoveField(
            model_name='twilioroom',
            name='assigned_to_coach',
        ),
        migrations.RemoveField(
            model_name='twilioroom',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='twilioroom',
            name='status',
        ),
    ]
