# Generated by Django 3.1.2 on 2021-01-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210112_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioroom',
            name='actio_session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.actiosession'),
            preserve_default=False,
        ),
    ]
