# Generated by Django 3.1.2 on 2021-01-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_twilioroom_actio_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twilioroom',
            name='access_token',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='twilioroom',
            name='unique_name',
            field=models.CharField(max_length=100),
        ),
    ]
