# Generated by Django 3.1.2 on 2021-01-12 21:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0019_auto_20210112_1728'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actiosession',
            unique_together={('coach', 'user', 'start_time', 'end_time', 'conducted_on')},
        ),
    ]
